import json

# Define the massive list ONCE. PASTE YOUR FULL LIST HERE.
GLOBAL_EXCLUDE_LIST = [
"Revolt Mixtape",
"FOX45 WBFF Baltimore - Free Live Local News Stream",
"10 NBC WJAR - (Providence RI*)",
"123 GO!",
"6 NEWS NBC - WJAC - (Johnstown PA*)",
"ABC 13 News - WLOS - (Asheville NC*)",
"ABC 5 - KSTP - (Minneapolis-St. Paul MN)",
"ABC 6 - WSYX - (Columbus OH*)",
"ABC 6 NEWS - KAAL - (Minnesota & Iowa)",
"ABC 7 - WJLA - (Washington DC*)",
"ABC NEWS 4 - WCIV - (Charleston SC*)",
"AWE plus",
"Al Jazeera",
"CBS 12 - WPEC - (West Palm Beach FL*)",
"CBS 2 News - KUTV - (Salt Lake City UT*)",
"CBS 21 News - WHP - (Harrisburg PA*)",
"CBS 4 News - KDBC - (El Paso TX*)",
"CBS Austin - KEYE - (Austin TX*)",
"Cowboy Movie Channel",
"FOX 11 - WLUK - (Green Bay WI*)",
"FOX 9 - WTOV - (Steubenville OH*)",
"Feva TV",
"Fox 25 - KOKH - (Oklahoma City OK*)",
"Fox 26 - KMPH - (Fresno CA*)",
"GenB TV",
"Gritos TV",
"Hipstr",
"Humor Mill TV",
"Hunt Fish TV",
"INTROUBLE",
"INWILD",
"Imagine PlayWorld",
"Just for Laughs",
"KATU 2 ABC - (Portland OR*)",
"KIDDO+",
"KOB 4 - (Albuquerque NM)",
"KOMO NEWS 4 - ABC - (Seattle WA*)",
"KSL-TV -5 - (Salt Lake City UT)",
"Law & Crime",
"Local 12 - WKRC - (Cincinnati OH*)",
"Mi Miedo Canal",
"Mi Raza Canal",
"My Money",
"NEWS 22 ABC - WKEF - (Dayton OH*)",
"NTD",
"News 3 NBC - KSNV - (Las Vegas NV*)",
"News 4 - WOAI - (San Antonio TX*)",
"News 9 - KWTV - (Oklahoma City OK)",
"News Channel 3 CBS - WWMT - (Grand Rapids MI*)",
"News On 6 - KOTV - (Tulsa OK)",
"News10NBC - WHEC - (Rochester NY)",
"NewsChannel 13 - WNYT - (Albany NY)",
"OAN plus",
"PursuitUP",
"RightNow TV",
"Salem News Channel",
"Slick Slime Sam",
"TBN",
"Teenvee",
"USA Today",
"Unleashed by DOGTV",
"WDIO ABC News - (Duluth MN)",
"WSBT 22 CBS - (South Bend IN*)",
"Western Bound",
"Wild TV: Nonstop Outdoor Action & Adventure",
"Zoomer TV",
    "Bizaar",
    "Hersphere",
    "Murdoch Mysteries",
    "Hollywire",
    "Inside Edition",
    "Kartoon Channel!",
    "FOX Sports",
    "Family Affair Channel",
    "21 Jump Street",
    "7th Heaven",
    "ALF",
    "ALLBLK",
    "Alfred Hitchcock",
    "Alien Nation by DUST",
    "Always Funny Videos",
    "American Ninja Warrior",
    "Ancient Aliens",
    "Andromeda",
    "Anger Management",
    "Animation+",
    "Are We There Yet?",
    "Auction Hunters",
    "Autopista",
    "Avatar",
    "Awkward",
    "Azteca",
    "BET Pluto TV",
    "BET Pluto",
    "BET x Tyler Perry Comedy",
    "BET x Tyler Perry Drama",
    "BET",
    "Baywatch",
    "Beauty and the Beast",
    "Becker",
    "Bes Kardes",
    "Beverly Hillbillies",
    "Beverly Hills 90210",
    "Black Cinema",
    "Black Classics",
    "Black Family Sitcoms",
    "Black TV",
    "Black Throwbacks",
    "Black Visionaries",
    "BlackPix",
    "Bloomberg",
    "Blue Bloods",
    "Bob Ross",
    "Boligjakten",
    "Bounce XL",
    "Brat TV",
    "C-SPAN",
    "CBS Sports",
    "CNBC",
    "COPS",
    "CSI",
    "CSI: Miami",
    "CSI: NY",
    "Camp Kulinaris",
    "Canela",
    "Car Chase",
    "Carol Burnett",
    "Caroline in the City",
    "Cash In The Attic",
    "Cerrado",
    "Chappelle's Show",
    "Charterfeber",
    "Cheers",
    "Cine",
    "Doctor Who",
    "Classica",
    "Conan O'Brien",
    "Confess by Nosey",
    "Corner Gas",
    "Criminal Minds",
    "Crímenes Verdaderos",
    "Cutlers Court",
    "Death Valley Days",
    "Declassified",
    "Degrassi",
    "Desi Play TV",
    "Designated Survivor",
    "Diagnosis Murder",
    "Dick Van Dyke",
    "Divorce Court",
    "Djazz",
    "Doc Martin",
    "Doctor Who",
    "Documentary + Science",
    "Dog Whisperer",
    "Dove Channel",
    "Dr. Phil",
    "Dynasty",
    "ESPN",
    "ET",
    "Ebony TV Drama",
    "Ebony",
    "Ed Sullivan",
    "Eggheads",
    "Español",
    "Estrella",
    "Eventyrlig Oppussing",
    "FGTeeV",
    "FILMEX",
    "Fact or Fiction",
    "FailArmy",
    "Family Ties",
    "Fangene på Fortet",
    "Feel Good Drama",
    "FilmRise Series Gratis",
    "Final Conflict",
    "Flashpoint",
    "Fox Business Network",
    "Fox News Channel",
    "Fox News",
    "Fox Soul",
    "FOX Soul",
    "Frasier",
    "FreeTV",
    "Funny AF",
    "GAGS",
    "Ghost Dimension",
    "Ghost Hunters",
    "Girlfriends",
    "Graham Norton",
    "Great American Adventures",
    "Grit Xtra",
    "Gunsmoke",
    "Hallmark Movies & More",
    "Hallmark Movies",
    "Hallmark",
    "Happy Days",
    "Hawaii Five-0",
    "Hearties",
    "Heartland",
    "Hell's Kitchen",
    "Highway to Heaven",
    "Homeful",
    "Hot Ones",
    "How To Use Pluto TV",
    "Hunter",
    "I Love Lucy",
    "In The Heat of the Night",
    "Inazuma Eleven",
    "Internacional",
    "Iron Chef",
    "JAG",
    "JAIL",
    "Johnny Carson TV",
    "Johnny Carson",
    "Judge Judy",
    "Just for Laughs Gags",
    "K-Content",
    "K-Stories",
    "KMOVIES",
    "Karadayi",
    "Key & Peele",
    "King of Queens",
    "LOL Network",
    "Latino",
    "Letterman TV",
    "Life with Derek",
    "Lifetime Love",
    "Lifetime Movies",
    "Little House on the Prairie",
    "Live Music",
    "Logo Pluto TV",
    "Love Boat",
    "Love Pets",
    "Lucha",
    "Luksusfellen",
    "MST3K",
    "MTV Pluto TV",
    "MTV Ridiculousness",
    "MVStv",
    "MacGyver",
    "Matlock",
    "McLeod's Daughters",
    "Medical Examiner",
    "Medium",
    "Melrose Place",
    "Miami",
    "Midsomer Murders",
    "Mission Impossible",
    "Misterios",
    "Moesha",
    "Movie Favorites By Lifetime",
    "Mr. Bean Animated",
    "MrBeast",
    "Mysteria",
    "Mystery Science Theater 3000",
    "MythBusters",
    "Mythbusters",
    "Mythical 24/7",
    "NCIS",
    "NHRA",
    "Nashville",
    "Nikita",
    "Ninja Warrior",
    "Nosey",
    "Novela",
    "Numb3rs",
    "OUTtv Proud",
    "Operation Repo",
    "Oro TV",
    "Out TV Proud",
    "Outside TV",
    "PBS",
    "PRIDEtv",
    "Paradise Hotel",
    "Paradise",
    "Paternity Court",
    "Películas",
    "Perry Mason",
    "Pet Collective",
    "Pluto TV Alien Invasion",
    "Pluto TV Buskis",
    "Pluto TV Merhaba Turkish Drama",
    "Pointless",
    "Pokémon",
    "Power Rangers",
    "Rakuten Viki",
    "Rawhide",
    "Red Green Channel",
    "Red Shoe Diaries",
    "RetroCrush",
    "Revry",
    "RiffTrax",
    "Robinsonekspedisjonen",
    "Robot Wars by MECH+",
    "Rookie Blue",
    "Rugby Pass TV",
    "Runtime Sangre Fría",
    "Sabrina the Teenage Witch",
    "Saved by the Bell",
    "Scorpion",
    "Shades of Black",
    "She Wrote",
    "Sister",
    "Sketchy AF",
    "Soul Flix",
    "Spark TV",
    "Stingray",
    "Super Channel Hearties",
    "Survivor",
    "Survivorman",
    "TVOAI",
    "Tales from the Darkside",
    "Taxi",
    "Telemundo",
    "Andy Griffith Show",
    "Beverly Hillbillies",
    "Bob Ross Channel",
    "Carol Burnett Show",
    "Conners",
    "Dick Van Dyke Show",
    "Ed Sullivan Show",
    "Good Wife",
    "Graham Norton Show",
    "The Lost World",
    "Love Boat",
    "Masked Singer",
    "Nanny",
    "Next Generation",
    "Original Series",
    "Red Green Channel",
    "Twilight Zone",
    "Three's Company",
    "Top Barça",
    "Tosh.0",
    "Touched by an Angel",
    "Trailer Park Boys",
    "Transformers",
    "U&Laughs",
    "Unspeakable",
    "ViX",
    "WAPA+",
    "Walker Texas Ranger",
    "WeTV",
    "Who's the Boss",
    "Who's the Boss?",
    "Wild 'N Out",
    "Wild at Heart",
    "Wildfire",
    "Wings",
    "Wipeout",
    "Yu-Gi-Oh!",
    "K-Drama",
    "K-Movie",
    "ÚN TV",
    "Sky Sports",
    "Sky Sport",
    "XITE",
    "WWE",
    "World Poker Tour",
    "Vevo",
    "Sports Channel",
    "UFC",
    "Top Chef",
    "Tiny House Nation",
    "TLC",
    "Top Gear",
    "TED",
    "TMZ",
    "This Old House",
    "Strawberry Shortcake",
    "VICE",
    "MTV",
    "Tennis",
    "Doctor Who",
    "Kungen",
    "Love Island",
    "Canal+ Sport",
    "Alien Nation by DUST",
    "Haunt TV",
    "HauntTV",
    "Mysterious Worlds",
    "HauntTV",
    "Haunt TV",
    "Unsolved Mysteries",
    "Sports",
    "DAZN",
    "Box Gamers",
    "Boxing TV",
    "BollyWood",
    "Disney",
    "SPORTS",
    "Bollywood",
    "Hindi",
    "HGTV",
    "NHK",
    "KPOP+",
    "Saudi",
    "Travel Channel",
    "Speedvision",
    "SSTV",
    "Scripps",
    "NDTV",
    "Islam Channel",
    "France 24",
    "National Geographic",
    "Fashion TV",
    "Euro News",
    "Smithsonian",
    "Reuters",
    "SPUK",
    "VTV",
    "Zee TV",
    "VSport",
    "Travel XP",
    "Swarnavahini",
    "Animal Planet",
    "Cheddar News",
    "PowerNation",
    "Design Network",
    "Jalwa",
    "Arabiya",
    "Premier League",
    "Football",
    "Toon Goggles",
    "Unbeaten",
    "CNN",
    "B4U",
    "Arabica",
    "BBS News",
    "BET Soul",
    "BET Gospel",
    "BET Jams",
    "BET East",
    "BET Her East",
    "beIN Sports",
    "Buzzr",
    "Nash Bridges",
    "Polly Pocket",
    "Toony Planet"
  ] 

# Load the template file
try:
    with open('config.template.json', 'r') as f:
        template_content = f.read()
except FileNotFoundError:
    print("Error: config.template.json file not found. Please create it.")
    exit(1)

# Replace the placeholder with the actual JSON-formatted list
# json.dumps() correctly formats the list as a JSON string
final_content = template_content.replace('{{GLOBAL_EXCLUDE_LIST}}', json.dumps(GLOBAL_EXCLUDE_LIST))

# Write the final config file that the app will use
with open('config.json', 'w') as f:
    f.write(final_content)

print("Success: config.json file generated!")
