import json

# Define the massive list ONCE. PASTE YOUR FULL LIST HERE.
GLOBAL_EXCLUDE_LIST = [
    "FILMEX",
    "MST3K",
    "Degrassi",
    "Ebony",
    "Canela",
    "FreeTV",
    "FailArmy",
    "Stargate",
    "Star Trek",
    "BlackPix",
    "Telemundo",
    "HSN",
    "QVC",
    "Latino",
    "Baywatch",
    "Hallmark",
    "K-Content",
    "Black Cinema",
    "Power Rangers",
    "Outside TV",
    "Black TV",
    "Dr. Phil",
    "Azteca",
    "FGTeeV",
    "Hot Ones",
    "Heartland",
    "PBS",
    "Grit Xtra",
    "Cerrado",
    "Johnny Carson",
    "Stingray",
    "Ed Sullivan",
    "Graham Norton",
    "Dick Van Dyke",
    "Revry",
    "ViX",
    "MrBeast",
    "Lucha",
    "MVStv",
    "COPS",
    "Autopista",
    "Spark TV",
    "NHRA",
    "In The Heat of the Night",
    "Estrella",
    "Español",
    "Pet Collective",
    "TVOAI",
    "WAPA+",
    "WeTV",
    "Películas",
    "American Ninja Warrior",
    "Great American Adventures",
    "Life with Derek",
    "Internacional",
    "The Masked Singer",
    "Top Barça",
    "ÚN TV",
    "Paternity Court",
    "Novela",
    "Red Green Channel",
    "Oro TV",
    "Soul Flix",
    "Misterios",
    "JAIL",
    "Carol Burnett",
    "Unspeakable",
    "FilmRise Series Gratis",
    "Medical Examiner",
    "Crímenes Verdaderos",
    "Runtime Sangre Fría",
    "Always Funny Videos",
    "Just for Laughs Gags",
    "LOL Network",
    "Lifetime Love",
    "Mythical 24/7",
    "Cine",
    "Designated Survivor",
    "Rakuten Viki",
    "Midsomer Murders",
    "Mysteria",
    "Transformers",
    "21 Jump Street",
    "ALLBLK",
    "Alfred Hitchcock",
    "Animation+",
    "Auction Hunters",
    "Avatar",
    "BET Pluto",
    "Beverly Hillbillies",
    "Black Classics",
    "Bounce XL",
    "Brat TV",
    "Car Chase",
    "Cash In The Attic",
    "Confess by Nosey",
    "Conan O'Brien",
    "CSI: Miami",
    "Dove Channel",
    "Family Ties",
    "FARSCAPE",
    "Final Conflict",
    "GAGS",
    "Hallmark Movies",
    "Hell's Kitchen",
    "Highway to Heaven",
    "Hunter",
    "K-Stories",
    "KMOVIES",
    "Letterman TV",
    "Lifetime Movies",
    "Mystery Science Theater 3000",
    "Operation Repo",
    "PRIDEtv",
    "RiffTrax",
    "Robot Wars by MECH+",
    "Rugby Pass TV",
    "Saved by the Bell",
    "Shades of Black",
    "She Wrote",
    "Sister",
    "Super Channel Hearties",
    "The Bob Ross Channel",
    "The Graham Norton Show",
    "The Lost World",
    "The Next Generation",
    "The Original Series",
    "Touched by an Angel",
    "Who's the Boss",
    "Frasier",
    "Cheers",
    "Rawhide",
    "Gunsmoke",
    "Pokémon",
    "Taxi",
    "NCIS",
    "CSI",
    "JAG",
    "Dynasty",
    "Nashville",
    "Djazz",
    "Classica",
    "Andromeda",
    "Declassified",
    "Wipeout",
    "Wildfire",
    "Scorpion",
    "Numb3rs",
    "Karadayi",
    "Boligjakten",
    "Flashpoint",
    "MacGyver",
    "Matlock",
    "Wings",
    "Survivorman",
    "Charterfeber",
    "Paradise",
    "Black Visionaries",
    "Ebony TV Drama",
    "Homeful",
    "BET x Tyler Perry Drama",
    "Luksusfellen",
    "Robinsonekspedisjonen",
    "Becker",
    "BET Pluto TV",
    "MythBusters",
    "MTV Pluto TV",
    "Little House on the Prairie",
    "Happy Days",
    "Love Boat",
    "Survivor",
    "Awkward",
    "Criminal Minds",
    "Blue Bloods",
    "Fangene på Fortet",
    "Eventyrlig Oppussing",
    "Paradise Hotel",
    "BET x Tyler Perry Comedy",
    "Black Throwbacks",
    "Hallmark Movies & More",
    "Camp Kulinaris",
    "Pluto TV Merhaba Turkish Drama",
    "Inazuma Eleven",
    "Yu-Gi-Oh!",
    "Live Music",
    "Nash Bridges",
    "ET",
    "Star Trek Deep Space Nine",
    "Star Trek Voyager",
    "Walker Texas Ranger",
    "ALLBLK Gems",
    "Logo Pluto TV",
    "Movie Favorites By Lifetime",
    "Beauty and the Beast",
    "Mission Impossible",
    "Diagnosis Murder",
    "Chappelle's Show",
    "Key & Peele",
    "Tosh.0",
    "Red Shoe Diaries",
    "BET",
    "The Twilight Zone",
    "Tales from the Darkside",
    "Caroline in the City",
    "Sabrina the Teenage Witch",
    "Judge Judy",
    "7th Heaven",
    "Iron Chef",
    "Doctor Who Classic",
    "Doc Martin",
    "The Good Wife",
    "Beverly Hills 90210",
    "Melrose Place",
    "CSI: NY",
    "Feel Good Drama",
    "Ghost Dimension",
    "Bes Kardes",
    "Pluto TV Alien Invasion",
    "Miami",
    "Alien Nation by DUST",
    "Pluto TV Buskis",
    "How To Use Pluto TV",
    "Documentary + Science",
    "Ghost Hunters",
    "Wild at Heart",
    "McLeod's Daughters",
    "Fact or Fiction",
    "King of Queens",
    "The Red Green Channel",
    "MTV Ridiculousness",
    "Anger Management",
    "I Love Lucy",
    "The Andy Griffith Show",
    "The Beverly Hillbillies",
    "The Love Boat",
    "Rookie Blue",
    "Medium",
    "Three's Company",
    "The Carol Burnett Show",
    "The Dick Van Dyke Show",
    "Perry Mason",
    "The Ed Sullivan Show",
    "Johnny Carson TV",
    "Nosey",
    "Mythbusters",
    "Out TV Proud",
    "South Park",
    "The Conners",
    "Pointless",
    "Eggheads",
    "Ninja Warrior",
    "Love Pets",
    "Dog Whisperer",
    "Desi Play TV",
    "Are We There Yet?",
    "Funny AF",
    "Moesha",
    "Girlfriends",
    "Wild 'N Out",
    "U&Laughs",
    "Corner Gas",
    "Hawaii Five-0",
    "Sketchy AF",
    "Nash Bridges",
    "RetroCrush",
    "Ancient Aliens",
    "The Nanny",
    "ALF"
  ] 

# Load the template file
try:
    with open('config.template.json', 'r') as f:
        template_content = f.read()
except FileNotFoundError:
    print("Error: config.template.json file not found. Please create it.")
    exit(1)

# Replace the placeholder with the actual JSON-formatted list
# json.dumps() correctly formats the list as a JSON string
final_content = template_content.replace('{{GLOBAL_EXCLUDE_LIST}}', json.dumps(GLOBAL_EXCLUDE_LIST))

# Write the final config file that the app will use
with open('config.json', 'w') as f:
    f.write(final_content)

print("Success: config.json file generated!")
