import json

# Define the massive list ONCE. PASTE YOUR FULL LIST HERE.
GLOBAL_EXCLUDE_LIST = [
"^Mystery Science Theater 3000$",
"Who's the Boss?",
"Family Hour TV",
"^Hunter$",
"Anger Management",
"Always Funny",
"BritBox Mysteries",
" 00s Replay",
" 48 Hours",
" 70s Cinema",
" 80s Rewind",
" 90s Throwback",
" American Crimes",
" Black Family Sitcoms",
" Classic Movies Channel",
" Court TV",
" Crime 360 by A&E",
" Dateline 24/7",
" Pluto TV Trending Now",
" Pluto TV True Crime",
" Pluto TV Westerns",
" The Addams Family",
" The New Detectives",
" The Walking Dead Universe",
" Universal Action",
" Universal Crime",
"#SayWhat?!",
"10 NBC WJAR - (Providence RI*)",
"123 GO!",
"21 Jump Street",
"24 Hour Free Movies",
"2900 Happiness",
"365BLK",
"50 Cent Action",
"6 NEWS NBC - WJAC - (Johnstown PA*)",
"7th Heaven",
"9 Story Presents: Garfield and Friends",
"A Haunting",
"A&E Crime 360",
"ABC 13 News - WLOS - (Asheville NC*)",
"ABC 5 - KSTP - (Minneapolis-St. Paul MN)",
"ABC 6 - WSYX - (Columbus OH*)",
"ABC 6 NEWS - KAAL - (Minnesota & Iowa)",
"ABC 7 - WJLA - (Washington DC*)",
"ABC NEWS 4 - WCIV - (Charleston SC*)",
"ALF",
"ALLBLK",
"AWE plus",
"Acorn TV Mysteries",
"Action Hollywood Movies",
"Addams Family",
"Al Jazeera",
"Alfred Hitchcock",
"Alien Nation by DUST",
"Alien Nation by DUST",
"Aliwko",
"Always Funny Videos",
"Always Funny",
"Amasian TV",
"American Crime Channel",
"American Crimes",
"American Gladiators by MGM",
"American Ninja Warrior",
"Ancient Aliens",
"Andromeda",
"Andy Griffith Show",
"Anger Management",
"Animal Planet",
"Animation+",
"Anime 24/7",
"Arabica",
"Arabiya",
"Are We There Yet?",
"Arthur",
"Asian Drama",
"At the Movies",
"Auction Hunters",
"Autopista",
"Avatar",
"Aventura",
"Awkward",
"Azteca",
"B4U",
"BBS News",
"BET East",
"BET Gospel",
"BET Her East",
"BET Jams",
"BET Pluto TV",
"BET Pluto",
"BET Soul",
"BET x Tyler Perry Comedy",
"BET x Tyler Perry Drama",
"BET",
"Barbie and Friends by Mattel",
"Barney and Friends",
"Baywatch",
"Beauty and the Beast",
"Becker",
"Bes Kardes",
"Beverly Hillbillies",
"Beverly Hills 90210",
"Bizaar",
"Black Cinema",
"Black Classics",
"Black Family Sitcoms",
"Black TV",
"Black Throwbacks",
"Black Visionaries",
"BlackPix",
"Bloodline Detectives Hosted by Nancy Grace",
"Bloomberg",
"Blue Bloods",
"Bob Ross Channel",
"Bob Ross",
"Bodas +",
"Boligjakten",
"BollyWood",
"Bollywood",
"Bondi Vet",
"Bounce XL",
"Box Gamers",
"Boxing TV",
"Brat TV",
"Bravo Vault",
"Buzzr",
"C-SPAN",
"CBC News",
"CBS 12 - WPEC - (West Palm Beach FL*)",
"CBS 2 News - KUTV - (Salt Lake City UT*)",
"CBS 21 News - WHP - (Harrisburg PA*)",
"CBS 4 News - KDBC - (El Paso TX*)",
"CBS Austin - KEYE - (Austin TX*)",
"CBS Sports",
"CNBC",
"CNN",
"CNÑ XPRESS",
"COPS",
"CSI",
"CSI: Miami",
"CSI: NY",
"CW Forever",
"CW Gold",
"Camp Kulinaris",
"Canal+ Sport",
"Canela",
"Car Chase",
"Carol Burnett Show",
"Carol Burnett",
"Caroline in the City",
"Cash In The Attic",
"Cerrado",
"Chaos on Cam by A&E",
"Chappelle's Show",
"Charterfeber",
"Cheddar News",
"Cheers",
"Christmas Plus",
"Cine",
"Cinépolis Channel",
"Cirque du Soleil",
"Classic Car Auctions",
"Classica",
"Cold Case Files by A&E",
"CombaTV",
"Comedy Dynamics",
"Conan O'Brien",
"Confess by Nosey",
"Conners",
"Construcciones Asombrosas",
"Continuum",
"Corner Gas",
"Cosmic Frontiers",
"Court TV Legendary Trials",
"Court TV",
"Cowboy Channel",
"Cowboy Classics",
"Cowboy Movie Channel",
"Creator Television",
"Crime & Justice",
"Crime Scene TV",
"Crime Scenes",
"Crime ThrillHer",
"Crimen",
"Criminal Minds",
"Crímenes Verdaderos",
"Cutlers Court",
"DAZN",
"DP World Tour",
"Danger TV",
"Dateline",
"Dawson's Creek",
"Death Valley Days",
"Declassified",
"Degrassi",
"Desi Play TV",
"Design Network",
"Designated Survivor",
"Diagnosis Murder",
"Dick Van Dyke Show",
"Dick Van Dyke",
"Disney",
"Divorce Court",
"Djazz",
"Doc Martin",
"Doctor Who",
"Documentary + Science",
"Documentary+",
"Dog Whisperer",
"Dove Channel",
"Dove",
"Dr. Phil",
"Dynasty",
"E! Keeping Up",
"ESPN",
"ET",
"Ebony TV Drama",
"Ebony",
"Ed Sullivan Show",
"Ed Sullivan",
"Eggheads",
"Español",
"Estrella",
"Euro News",
"Eventyrlig Oppussing",
"Expedientes Sobrenaturales",
"F1 Channel",
"FARSCAPE",
"FGTeeV",
"FILMEX",
"FLOU Detonación",
"FOX 11 - WLUK - (Green Bay WI*)",
"FOX 9 - WTOV - (Steubenville OH*)",
"FOX Soul",
"FOX Sports",
"FOX45 WBFF Baltimore - Free Live Local News Stream",
"FRANCE 24",
"Fact or Fiction",
"FailArmy",
"Family Affair Channel",
"Family Ties",
"Fangene på Fortet",
"Farscape",
"Fashion TV",
"Feel Good Drama",
"Feva TV",
"FilmRise Action",
"FilmRise Free Movies",
"FilmRise Music",
"FilmRise Series Gratis",
"FilmRise True Crime",
"Final Conflict",
"Flashpoint",
"Football",
"Forensic Files",
" Forensic Files",
"Fox 25 - KOKH - (Oklahoma City OK*)",
"Fox 26 - KMPH - (Fresno CA*)",
"Fox Business Network",
"Fox News Channel",
"Fox News",
"Fox Soul",
"France 24",
"Frasier",
"Free Movies Plus",
"FreeTV",
"Funny AF",
"Funny Or Die Inc.",
"GAGS",
"GOLFPASS",
"Galxy TV",
"Game & Fish TV",
"GameTVGO",
"Gata Salvaje",
"GenB TV",
"Ghost Dimension",
"Ghost Hunters",
"Girlfriends",
"Gone Fishing",
"Good Wife",
"Graham Norton Show",
"Graham Norton",
"Gravitas Adrenaline",
"Gravitas Documentaries",
"Gravitas Movies",
"Great American Adventures",
"Green Acres",
"Grit Xtra",
"Gritos TV",
"Gunsmoke",
"HGTV",
"Hallmark Movies & More",
"Hallmark Movies",
"Hallmark",
"Happy Days",
"Hardcore Pawn",
"Haunt TV",
"HauntTV",
"Hawaii Five-0",
"Hearties",
"Heartland",
"Hell's Kitchen",
"Hersphere",
"Hersphere",
"Highway to Heaven",
"Hindi",
"Hipstr",
"History & Warfare",
"Hit Sitcoms",
"Hollywire",
"Homeful",
"Hot Ones",
"Hot Wheels Action",
"How To Use Pluto TV",
"Humor Mill TV",
"Humor Mill",
"Hunt Fish TV",
"Hunter",
"I Love Lucy",
"IFC Films Picks",
"INTROUBLE",
"INWILD",
"ION Plus",
"ION",
"ITV Deportes",
"Imagine PlayWorld",
"In The Heat Of The Night by MGM",
"In The Heat of the Night",
"Inazuma Eleven",
"Inside Edition",
"Internacional",
"Investigation",
"Iron Chef",
"Islam Channel",
"JAG",
"JAIL",
"Jalwa",
"Johnny Carson TV",
"Johnny Carson",
"Jubao",
"Judge Judy",
"Just For Laughs Gags",
"Just for Laughs Gags",
"Just for Laughs",
"K-Baseball TV",
"K-Content",
"K-Drama",
"K-Movie",
"K-Stories",
"KATU 2 ABC - (Portland OR*)",
"KIDDO+",
"KMOVIES",
"KOB 4 - (Albuquerque NM)",
"KOMO NEWS 4 - ABC - (Seattle WA*)",
"KPOP+",
"KSL-TV -5 - (Salt Lake City UT)",
"Karadayi",
"Kartoon Channel!",
"Key & Peele",
"Kim's Convenience",
"King of Queens",
"Kungen",
"LOL Network",
"LOL! Network",
"LX Home Streaming",
"Latino",
"Law & Crime",
"Lawless",
"Letterman TV",
"Life Down Under",
"Life with Derek",
"Lifetime Love",
"Lifetime Movies",
"Little House on the Prairie",
"Live Music",
"Live PD Presents",
"Local 12 - WKRC - (Cincinnati OH*)",
"Logo Pluto TV",
"Los Asesinatos de Midsomer",
"Love After Lockup We TV",
"Love Boat",
"Love Island",
"Love Pets",
"Love Thy Neighbor",
"Lucha",
"Luksusfellen",
"MGM Presents",
"MGM Presents: Action",
"MGM Presents: Westerns",
"MHz Now",
"MI-5",
"MOVIESPHERE",
"MST3K",
"MTV Pluto TV",
"MTV Ridiculousness",
"MTV",
"MVStv",
"MacGyver",
"MagellanTV Wildest",
"Masked Singer",
"Matlock",
"Mattel Jr.",
"McLeod's Daughters",
"Medical Examiner",
"Medium",
"Melrose Place",
"Mi Miedo Canal",
"Mi Raza Canal",
"Miami",
"Midnight Pulp",
"Midsomer Murders",
"Million Dollar Dream Home",
"Million Dollar Listing Vault",
"Miramax Movie Channel",
"Mission Impossible",
"Misterios",
"Modern Innovations by History",
"Moesha",
"MotoGP Channel",
"Movie Favorites By Lifetime",
"Movie Favorites by Lifetime",
"Movieitaly Channel",
"Mr. Bean Animated",
"Mr. Bean Live Action",
"Mr. Bean",
"MrBeast",
"Murdoch Mysteries",
"My Little Pony",
"My Money",
"MyTime Movie Network",
"Mysteria",
"Mysterious Worlds",
"Mystery Science Theater 3000",
"MythBusters",
"Mythbusters",
"Mythical 24/7",
"NBC 4 Washington News",
"NCIS",
"NDTV",
"NESN NATION",
"NEW K.MOVIES",
"NEWS 22 ABC - WKEF - (Dayton OH*)",
"NHK",
"NHRA",
"NTD",
"Nanny",
"Nash Bridges",
"Nashville",
"National Geographic",
"National Lampoon",
"News 3 NBC - KSNV - (Las Vegas NV*)",
"News 4 - WOAI - (San Antonio TX*)",
"News 9 - KWTV - (Oklahoma City OK)",
"News Channel 3 CBS - WWMT - (Grand Rapids MI*)",
"News On 6 - KOTV - (Tulsa OK)",
"News10NBC - WHEC - (Rochester NY)",
"NewsChannel 13 - WNYT - (Albany NY)",
"Next Generation",
"Nikita",
"Ninja Warrior",
"Nosey",
"Novela",
"Numb3rs",
"OAN plus",
"ONE Championship TV",
"OUTtv Proud",
"OnDemandChina",
"Operation Repo",
"Original Series",
"Oro TV",
"Out TV Proud",
"OuterSphere by Lionsgate",
"Outlaw",
"Outside TV",
"Oxygen True Crime Archives",
"PBS",
"PGA TOUR",
"PLL Network",
"PRIDEtv",
"Paradise Hotel",
"Paradise",
"Paternity Court",
"PeliMex",
"Películas",
"Perry Mason",
"Pet Collective",
"Pink Panther",
"Plex24",
"Pluto TV Alien Invasion",
"Pluto TV Buskis",
"Pluto TV Merhaba Turkish Drama",
"Pointless",
"Pokémon",
"Polly Pocket",
"Popular Science",
"Portlandia",
"Power Rangers",
"PowerNation",
"Premier League",
"PursuitUP",
"RACER International",
"RACER Select",
"RCM",
"RCN Noticias",
"Rakuten Viki",
"Rawhide",
"Real Crime",
"Real Housewives Vault",
"Red Green Channel",
"Red Shoe Diaries",
"RetroCrush",
"Reuters",
"Revolt Mixtape",
"Revry",
"RiffTrax",
"RightNow TV",
"Robinsonekspedisjonen",
"Robot Wars by MECH+",
"Rookie Blue",
"Rugby Pass TV",
"Runtime Sangre Fría",
"Runtime",
"SNL Vault",
"SPORTS",
"SPUK",
"SSTV",
"Sabrina the Teenage Witch",
"Salem News Channel",
"Samuel Goldwyn Channel",
"Saudi",
"Saved by the Bell",
"Scorpion",
"Scripps",
"Shades of Black",
"Shaun the Sheep and Friends",
"She Wrote",
"Sheriffs: El Dorado County",
"Shout! Movies",
"Shout! TV",
"Sister",
"Sketchy AF",
"Sky Sport",
"Sky Sports",
"Slick Slime Sam",
"Slightly Off IFC",
"Smithsonian",
"Soul Flix",
"Spark TV",
"Sparkle Movies - Light & Love",
"Speedvision",
"Sports Channel",
"Sports",
"Stars Central",
"Stingray",
"Storage Wars by A&E",
"Stories by AMC",
"Strawberry Shortcake",
"Super Channel Hearties",
"Survivor",
"Survivorman",
"Swarnavahini",
"TBN",
"TED",
"TLC",
"TMZ",
"TV One Crime & Justice",
"TVB Pearl Drama",
"TVOAI",
"Tales from the Darkside",
"Taxi",
"Teenvee",
"Telemundo",
"Teleonce America",
"Tennis",
"The Addams Family",
"The Asylum",
"The Black Effect",
"The Bold and the Beautiful",
"The Doctors",
"The Ellen Channel",
"The Emeril Lagasse Channel",
"The FBI Files",
"The First 48",
"The Librarians",
"The Lost World",
"The Martha Stewart Channel",
"The New Detectives",
"The Osbournes",
"The Outer Limits",
"The Outpost",
"The Walking Dead Espanol",
"The Walking Dead Universe",
"This Old House",
"Three's Company",
"Tiny House Nation",
"Todo Crimen",
"Todo Drama",
"Toon Goggles",
"Toony Planet"
"Top Barça",
"Top Chef",
"Top Gear",
"Tosh.0",
"Touched by an Angel",
"Trailer Park Boys",
"Transformers",
"Travel Channel",
"Travel XP",
"Tribeca Channel",
"Triton Poker",
"TruBlu",
"True Crime Now",
"TuDiscovery",
"TuWarner",
"Twilight Zone",
"U&Laughs",
"UFC",
"USA Today",
"Unbeaten",
"Unleashed by DOGTV",
"Unsolved Mysteries",
"Unspeakable",
"VICE",
"VSport",
"VTV",
"Vevo",
"ViX",
"Vidas Extremas",
"Vive Kanal D Drama",
"WAPA+",
"WDIO ABC News - (Duluth MN)",
"WSBT 22 CBS - (South Bend IN*)",
"WWE",
"Walker Texas Ranger",
"WeTV",
"Wedotv Amor Piel Salvaje",
"Weeds & Nurse Jackie",
"Wendy Williams",
"Western Bound",
"Wild 'N Out",
"Wild TV: Nonstop Outdoor Action & Adventure",
"Wild at Heart",
"Wildfire",
"Wings",
"Wipeout",
"Women Behind Bars",
"World Poker Tour",
"XITE",
"Yu-Gi-Oh!",
"Z Nation",
"Zee BollyWorld",
"Zee TV",
"Zoomer TV",
"^50 Cent Action$",
"^Funny Or Die Inc.$",
"beIN Sports",
"ÚN TV",
  ]

# Load the template file
try:
    with open('config.template.json', 'r') as f:
        template_content = f.read()
except FileNotFoundError:
    print("Error: config.template.json file not found. Please create it.")
    exit(1)

# Replace the placeholder with the actual JSON-formatted list
# json.dumps() correctly formats the list as a JSON string
final_content = template_content.replace('{{GLOBAL_EXCLUDE_LIST}}', json.dumps(GLOBAL_EXCLUDE_LIST))

# Write the final config file that the app will use
with open('config.json', 'w') as f:
    f.write(final_content)

print("Success: config.json file generated!")
